### PR TITLE
Issue#303/pdf lower upper case

### PR DESCRIPTION
**Pull request by klues**

### CODE REVIEW

**Review by filipeferreira-dev — APPROVED** [review]

**Comment by klues** [comment]
@filipeferreira-dev thanks for looking at this! I've created it along with @tchjohanna while showing her the codebase. However, I think it's not completely finished, since the uppercase labels in the resulting PDFs are often too big, so probably it's needs some refinement (where you're welcome to contribute, if @tchjohanna doesn't want to continue with it).

**Comment by tchjohanna** [comment]
import { GridData } from '../model/GridData';
import { GridImage } from '../model/GridImage';
import { i18nService } from './i18nService';
import { imageUtil } from '../util/imageUtil';
import { GridElement } from '../model/GridElement';
import { util } from '../util/util';
import { dataService } from './data/dataService.js';
import { MetaData } from '../model/MetaData.js';
import { arasaacService } from './pictograms/arasaacService.js';

// Assure-toi que jsPDF est correctement importé
import { jsPDF } from 'jspdf';

let printService = {};
let gridInstance = null;

let pdfOptions = {
    docPadding: 5,
    footerHeight: 8,
    textPadding: 3,
    elementMargin: 1,
    imgMargin: 1,
    imgHeightPercentage: 0.8
};

let patternFontMappings = [
    {
        pattern: /^[\u0400-\u04FF]+$/,
        font: '/app/fonts/Arimo-Regular-Cyrillic.ttf'
    }
];

printService.initPrintHandlers = function () {
    window.addEventListener('beforeprint', () => {
        if (gridInstance) {
            $('#grid-container').css({ width: '27.7cm', height: '19cm' });
            gridInstance.autosize();
        }
    });
    window.addEventListener('afterprint', () => {
        if (gridInstance) {
            $('#grid-container').css({ width: '', height: '' });
            gridInstance.autosize();
        }
    });
};

printService.setGridInstance = function (instance) {
    gridInstance = instance;
};

printService.gridsToPdf = async function (gridsData, options = {}) {
    let doc = new jsPDF({ orientation: 'landscape', compress: true });

    // Charge la police si spécifié
    if (options.fontPath) {
        await loadFont(options.fontPath, doc);
    }

    try {
        await generatePDF(gridsData, options, doc);
    } catch (error) {
        console.error('Erreur lors de la génération du PDF :', error);
    }
};

async function generatePDF(grids

**Comment by tchjohanna** [comment]
I've made several changes to this JavaScript code snippet to improve clarity and maintainability. Firstly, I've ensured that variables such as `i18nService`, `dataService`, and `imageUtil` are properly initialised to indicate how they are included in the script, thereby enhancing readability. Next, I checked that `jsPDF` was correctly imported at the start of the script, as it is used in several places outside the `printService.gridsToPdf` function. Regarding the management of asynchronous operations, I've made sure that functions such as `addImageToPdf` are waited for (`await`) in order to avoid unmanaged promises and to ensure that the PDF generation process doesn't continue until these operations have been completed. I've also added error handling to asynchronous functions to better manage exceptions and potential API call failures. For calculations of element sizes and positions, I've simplified or broken down these calculations into smaller functions for better management. Finally, I've optimised the loading and use of fonts by ensuring that they are loaded before they are used in the document, thus avoiding runtime errors.

**Comment by tchjohanna** [comment]
I'm off to work now, but I'll resume work on this project this evening. Before posting my changes, I'd like to share my code here as a comment. I have some doubts about my work and I'd really appreciate your feedback to make sure everything's in order. Thanks in advance for your help and advice.

**Comment by klues** [comment]
Thanks for your work. Please don't be afraid of pushing your code changes to this branch. Then I can clearly see the diff and also can give you feedback about it. That's exactly the purpose of pull requests. With the code in the comment it's much more difficult to give feedback.

Just one thing: [importing jsPDF dynamically](https://github.com/asterics/AsTeRICS-Grid/blob/9b85264bd0c4e62fbd7681a55192f0e75ef051f5/src/js/service/printService.js#L63) is on purpose in order to prevent loading jsPDF (which is a quite big library) if it's not used (if the users don't export any pdfs).

**Comment by tchjohanna** [comment]
Could I submit my changes via a pull request from my fork, even if I don't have the rights to push directly to the original repository? This would allow the repository maintainers to see my changes, comment on them and possibly integrate them.

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
johannacastagna@Air-de-Johanna AsTeRICS-Grid % git push -u origin johanna-issue303

ERROR: Permission to asterics/AsTeRICS-Grid.git denied to tchjohanna.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
johannacastagna@Air-de-Johanna AsTeRICS-Grid % git remote -v

origin  git@github.com:asterics/AsTeRICS-Grid.git (fetch)
origin  git@github.com:asterics/AsTeRICS-Grid.git (push)
johannacastagna@Air-de-Johanna AsTeRICS-Grid % 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by tchjohanna** [comment]
https://github.com/asterics/AsTeRICS-Grid/pull/393#issue-2303422673

**Pull request closed without merging**
