### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by klues**

### CODE REVIEW

**Comment by deinhofer** [comment]
Did you do a translation test?
Unfortunately it seems that the PR is based on the old i18n.ro.json file. Did you click synchronize in crowdin before?

**Comment by klues** [comment]
I think the reason for the merge conflict was an invalid translation key that somehow happened (it's already in master, so I assume you've checked it in): https://github.com/asterics/AsTeRICS-Grid/commit/5c29d9f580376b216c60bd1baf976e4c63b42585

Now the contents of this PR seem to be the things that are already in master (which I don't really understand) according to the diff e.g. the line:
`"CONFIRM_REMOVE_USER": "Sigur： Sigur： să deconec： utilizatorul \"{0}\"? Acest lucru nu va șterge utilizatorul în sine, ci toate datele utilizatorului stocate pe acest dispozitiv.",`
was added, however it's already in master: https://github.com/asterics/AsTeRICS-Grid/blob/master/app/lang/i18n.ro.json#L37
So I don't understand why Github is showing the diff that it shows.

But as you see it seems that the translations added by you / DeepL still have errors (`Sigur： Sigur： să deconec：...`) - that's the reason why I'm a little bit sceptical about automatic translations and think that often English is better than an automatic translation where we don't know if it's correct.

**Comment by deinhofer** [comment]
Using DeepL really speeds up the translation a lot, but putting in the whole file obviously sometimes also touches the keys, so this is absolutely not good. The next time I will do it individually, but also locally because with crowdin, the entering process of the translation is very slow.

In the end, there should be a native review of course. I will ask the Romanian guys to do that. But I think it's no problem if the translation is not perfect by now, because people can always switch back to English and correct the translations step by step.

I suggest to fix the following entries now:
```
"selectAlreadyUsedLanguages": "Selec： limbile deja folosite",
"selectAlreadyUsedLanguages": "Selectaţi limbile deja folosite",

"CONFIRM_REMOVE_USER": "Sigur： Sigur： să deconec： utilizatorul \"{0}\"? Acest lucru nu va șterge utilizatorul în sine, ci toate datele utilizatorului stocate pe acest dispozitiv.",
"CONFIRM_REMOVE_USER": "Sigur doriţi să deconectaţi utilizatorul \"{0}\"? Acest lucru nu va șterge utilizatorul în sine, ci toate datele utilizatorului stocate pe acest dispozitiv.",

"CONFIRM_DELETE_DICT": "Sigur είναι să ștergeți dicționarul \"{0}\"?",
"CONFIRM_DELETE_DICT": "Sigur doriţi să ştergeţi dicţionarul \"{0}\"?",

"CONFIRM_DELETE_ALL_ELEMS": "Sunteți sigur că είναι să ștergeți toate elementele din grila curentă?",
"CONFIRM_DELETE_ALL_ELEMS": "Sunteţi sigur că doriţi să ştergeţi toate elementele din grila curentă?",
```

Commit them in this branch and then merge again.
Then everything should be fine.

**Comment by klues** [comment]
> In the end, there should be a native review of course. I will ask the Romanian guys to do that. But I think it's no problem if the translation is not perfect by now, because people can always switch back to English and correct the translations step by step.

Ok, crowdin could also be used to approve the translations. They have an "approve" functionality.

> I suggest to fix the following entries now:

Ok, please do it via the crowdin UI, I think that's the fastest now.

**Comment by deinhofer** [comment]
@klues I resolved the conflict, so I think it's ready to merge, please check it.

**Comment by klues** [comment]
OK, looks good, thanks!

**Pull request merged**
