### PR TITLE
Deinhofer/puckjs basic support

### PR DESCRIPTION
**Pull request by deinhofer**
added basic support that let's you send puck.js javascript commands to be executed at puck.js.

This can be e.g.

## turn on/off LED
See [Puck.js LEDs](https://www.espruino.com/Puck.js#leds)

```
digitalWrite(LED1,1);
digitalWrite(LED1,0);

or

LED1.set();
LED1.reset();
```

## switch on/off integrated FET

See [Puck.js FET tutorial](https://www.espruino.com/Puck.js+FET) 
```
FET.set();
FET.reset();
```

### CODE REVIEW

**Comment by deinhofer** [comment]
How could I know test it on other platforms now? e.g. Android, iOS,...
Do we have to release it for that?

**Comment by klues** [comment]
Thanks for the contribution! 👍 

Please:
1. try if it's possible to load `puck.js` dynamically using webpack, maybe this helps: https://medium.com/front-end-weekly/webpack-and-dynamic-imports-doing-it-right-72549ff49234
2. if you find a solution for (1), run `npm run build` in order to generate all assets created by webpack
3. run `node scripts/getServiceWorkerCachePaths.js` and then copy the contents of [serviceWorkerPaths.txt](https://github.com/asterics/AsTeRICS-Grid/blob/master/scripts/serviceWorkerPaths.txt) to [serviceWorker.js#L20](https://github.com/asterics/AsTeRICS-Grid/blob/master/serviceWorker.js#L20). This is needed in order to cache all files including `puck.js` (or the assets generated by webpack) at first start and making the whole app usable offline.
4. please add the documentation of the action to [documentation_user/05_actions.md](https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/05_actions.md)

**Comment by klues** [comment]
> How could I know test it on other platforms now? e.g. Android, iOS,... Do we have to release it for that?

1. you can start it locally, connect your devices to the same network, and navigate to `http:\\<ip-of-your-dev-pc>:9095` within the browser of the testing device.
2. After merging, we can do a release to https://grid.asterics.eu/latest

**Comment by deinhofer** [comment]
> > How could I know test it on other platforms now? e.g. Android, iOS,... Do we have to release it for that?
> 
>     1. you can start it locally, connect your devices to the same network, and navigate to `http:\\<ip-of-your-dev-pc>:9095` within the browser of the testing device.
> 
>     2. After merging, we can do a release to https://grid.asterics.eu/latest

Unfortunately, I could not test it this way as the web bluetooth detection only works on an https site. 
But I have temporarily deployed it to https://studyathome.technikum-wien.at:8090/ so that it can be tested from anywhere.

**Comment by deinhofer** [comment]
I have found a way of how to use the Infrared database in combination with this PR easily:
I have forked the [puckmote](https://github.com/asterics/puckmote) project and added an output message showing the infrared command to be sent to the puck-js device. This command can simply be copied and pasted in as puck-js action in AG.

puck-js-ircmd

We could also add your [fix for the 'Unknown protocol error'](https://github.com/benfoxall/puckmote/issues/4).
Here is the deployed page of the fork: [https://asterics.github.io/puckmote/](https://asterics.github.io/puckmote/)

Additionally it would be possible to do toy control (turn on/off toy,...) with this PR by using:
```javascript
FET.set();
FET.reset();
```

See [Puck.js FET tutorial](https://www.espruino.com/Puck.js+FET)

Could you please do a review, so that we could merge within the next weeks?

**Review by klues — CHANGES_REQUESTED** [review]
Thanks for your contribution! Great that you found out how to use IR-codes from puckmote and the possibility of controlling external toys! Additionally to my comments in the code, please also add some documentation to https://github.com/asterics/AsTeRICS-Grid/blob/master/docs/documentation_user/05_actions.md . I think then we can merge (I didn't do any functional tests).

For the future we should find out, how we can create a better system for integrating new actions, which (1) make the effort for integration smaller (fewer files to change) and (2) better organizing action types, because the list is now getting quite long.

**Comment by klues** [comment]
I've merged this branch to branch `latest`, plese add the documentation there. I'll finish the rest.

**Pull request closed without merging**
