### PR TITLE
Adding openHAB integration

### PR DESCRIPTION
**Pull request by NotTheCaptain**
Adding openHAB in AsTeRICS-Grid for controlling your local openHAB installation without ARE.

Following item types are currently supported:

- Switches
- Dimmer
- Color Items
- Roller shutters
- Temperature
- Media Players

### CODE REVIEW

**Comment by klues** [comment]
Thanks for the PR!
I've improved some things on this branch: https://github.com/asterics/AsTeRICS-Grid/tree/adding-openhab-integration with this commit: https://github.com/asterics/AsTeRICS-Grid/commit/a8d28b5416037ca097792b516f82b4067a0f48da

These were my changes:
* merged the current master into this branch in order to resolve merge conflicts
* using Bootstrap CSS classes instead of Skeleton CSS because it's more flexible
* optimized styling for mobile and desktop view
* using constants instead of plain strings where possible
* using type `Number` instead of `Number:Temperature` since both OH2 and OH3 didn't return any items with type `Number:Temperature` for my tests. And maybe it's also good to be able to set other numbers.
* much simpler template for additional input fields (range/color), see https://github.com/asterics/AsTeRICS-Grid/commit/a8d28b5416037ca097792b516f82b4067a0f48da#diff-84decbf7995b430bf602adc0f0b942955bea5f57d334a932f9e08be7f8655a3aR80 - all custom number input are now using the range input, the special case for temperature was removed, see above.
* some simplifications in JS, e.g. filtering for both item type and search text in this method: https://github.com/asterics/AsTeRICS-Grid/commit/a8d28b5416037ca097792b516f82b4067a0f48da#diff-84decbf7995b430bf602adc0f0b942955bea5f57d334a932f9e08be7f8655a3aR159 - no filtering in template anymore.
* added `TOGGLE` action for item type "Switch"

please test and afterwards there are two possibilities:
1. close this PR and open a new one for the new branch https://github.com/asterics/AsTeRICS-Grid/tree/adding-openhab-integration
2. Merging this branch back to your fork and keep this PR open (will result in a merged PR opened by you, if you mind github statistics)

Anyways I'll add you as contributor to this repo, so that you could also push to the new branch or create a new one for https://github.com/asterics/AsTeRICS-Grid/issues/212

**Comment by NotTheCaptain** [comment]
I will use option 2 for the PR (just this one time for the statistics ;-) ).
Overall very clean code, I like it. Didn't know that `TOGGLE` was a valid command.

Only thing I noticed, was the change from `Number:Temperature` to `Number`.
I tested my local openHAB and the SLL openHAB, and both don't show any temperature related items anymore.
`Number:Temperature` is a unique type (see https://www.openhab.org/docs/concepts/items.html#items) and the channel of an item, which controls the temperature is auto-configured to `Number:Temperature` most of the item.
I really don't know why it didn't returned any items for you but according to https://github.com/NotTheCaptain/AsTeRICS-Grid/commit/e0722057bded08bf56f104ccc5d424fc6ae3a63b, you used openHAB 2 which I didn't tested.
openHAB 2 doesn't have `Number:Temperature` items (see [openHAB 2 types](https://v2.openhab.org/docs/configuration/items.html#type)).

Therefore, I will reintroduce this item type to your code so it will work with at least openHAB 3 types.

**Comment by NotTheCaptain** [comment]
Re-added `Number:Temperature` (see https://github.com/asterics/AsTeRICS-Grid/pull/209/commits/8bad4b12f83f6a3da9cc5133253520d8ccc3438f) and confirmed that I am able to control the temperature in both my local openHAB and openHAB3 at the SLL.

There are some items at SLL that control the temperature which have the type `Number`, other ones have the type `Number:Temperature`. Our SLL-openHAB may not be the best testing ground... ;)

@klues If you are happy with my addition than we could merge this PR.

**Comment by klues** [comment]
> Overall very clean code, I like it. Didn't know that TOGGLE was a valid command.

I just thought that it would make sense for a switch, tested it and it worked ;)

> Number:Temperature is a unique type (see https://www.openhab.org/docs/concepts/items.html#items) and the channel of an item, which controls the temperature is auto-configured to Number:Temperature most of the item.

OK, I've tested both OH3 and OH2 for SLL and both of them don't include items with `Number:Temperature` - strange. This states that there are some more possible types: https://www.openhab.org/docs/concepts/units-of-measurement.html#quantitytype
So a solution where all these types are working would be to keep "Number" as type for filtering and use [.startsWith()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith?retiredLocale=de) in the code for all checks where the type is compared. However we can also leave it as it is and change this any time a user complains that he/she cannot filter for eg. `Number:Length` (what probably will never happen) ;)

One more question before merging:
What about the item type "color"? The possible actions for it are `["ON", "OFF", "INCREASE", "DECREASE", "CUSTOM_VALUE", "CUSTOM_COLOR"]` - what does "increase" and "decrease" do for a color item? Or is a color item always a LED which can be dimmed with "increase" and "decrease"?

**Comment by NotTheCaptain** [comment]
> I just thought that it would make sense for a switch, tested it and it worked ;)

Wasn't even mentioned in the docs.

> So a solution where all these types are working would be to keep "Number" as type for filtering and use [.startsWith()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith?retiredLocale=de) in the code for all checks where the type is compared. However we can also leave it as it is and change this any time a user complains that he/she cannot filter for eg. `Number:Length` (what probably will never happen) ;)

Yeah, there are about 20+ `Number:*` - Types

> One more question before merging: What about the item type "color"? The possible actions for it are `["ON", "OFF", "INCREASE", "DECREASE", "CUSTOM_VALUE", "CUSTOM_COLOR"]` - what does "increase" and "decrease" do for a color item? Or is a color item always a LED which can be dimmed with "increase" and "decrease"?

I think, this depends on how a color item is implemented in openHAB. At home, my Shelly Color Bulb has it's own channel for white dimming (which would be a dimmer, not a color item). Dimming is mostly support, when a color item is in white mode. I think, we could  remove "increase" and "decrease" and wait for someone with a real use case for this. I personally haven't found an usage for it, I just took what was described in the docs.

**Comment by klues** [comment]
> Dimming is mostly support, when a color item is in white mode. I think, we could remove "increase" and "decrease" and wait for someone with a real use case for this. I personally haven't found an usage for it, I just took what was described in the docs.

OK, then it's good to remove it, thanks.

Regarding formatting, could you maybe try to import this `.editorconfig` file in your VSCode, so that hopefully the indentation will be the same as my config from IntellJIDEA: [editorconfig.zip](https://github.com/asterics/AsTeRICS-Grid/files/10277322/editorconfig.zip) (using .zip since GitHub doesn't allow files starting with `.`)
According to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003100859-Export-IDEA-style-settings-for-VSCode it should work.

**Comment by NotTheCaptain** [comment]
> Regarding formatting, could you maybe try to import this `.editorconfig` file in your VSCode, so that hopefully the indentation will be the same as my config from IntellJIDEA: [editorconfig.zip](https://github.com/asterics/AsTeRICS-Grid/files/10277322/editorconfig.zip) (using .zip since GitHub doesn't allow files starting with `.`) According to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003100859-Export-IDEA-style-settings-for-VSCode it should work.

Done. Btw I still use IntelliJ :)

**Comment by klues** [comment]
Thanks for your work, I've merged 👍 
I've added some improvements to the docs here, which I'll also merge now: https://github.com/asterics/AsTeRICS-Grid/commit/cb8c9efba6cf9395259cf90d9ca04101e2c78ba6

**Pull request merged**
